# Generated by Django 4.2.4 on 2023-10-12 09:49

from django.db import migrations, models
import not_a_boring_blog.models.post


class Migration(migrations.Migration):

    dependencies = [
        ('not_a_boring_blog', '0019_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=not_a_boring_blog.models.post.upload_to),
        ),
    ]
